apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qod
  namespace: qod
spec:
  path: /
  to:
    kind: Service
    name: qod-web
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
