apiVersion: v1
kind: Service
metadata:
  name: qod-web
  labels:
    app: qod-web
    tier: ui
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: qod-web
